/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SyncGraphPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var SyncGraphPlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.addCommand({
      id: "sync-graph-colorgroups-to-localgraph",
      name: "Sync Graph Groups Settings to Local Graph",
      callback: async () => {
        await this.syncGlobalToLocal();
      }
    });
  }
  async syncGlobalToLocal() {
    const configDir = this.app.vault.configDir;
    const graphConfigPath = (0, import_obsidian.normalizePath)(configDir + "/graph.json");
    if (true) {
      const graphConfigJson = await this.app.vault.adapter.read(graphConfigPath);
      const graphConfig = JSON.parse(graphConfigJson);
      const graphColorGroups = graphConfig.colorGroups;
      this.getLocalGraphLeaves().forEach((leaf) => {
        this.setColorGroups(leaf, graphColorGroups);
      });
    } else {
    }
  }
  getLocalGraphLeaves() {
    return this.app.workspace.getLeavesOfType("localgraph");
  }
  setColorGroups(localGraphLeaf, colorGroups) {
    const viewState = localGraphLeaf.getViewState();
    viewState.state.options.colorGroups = colorGroups;
    localGraphLeaf.setViewState(viewState);
  }
};
